### ISSUE TITLE
Missing from AssetLib

### ISSUE THREAD

**Issue by jasontherand** [christinoleo/godot-google-font-explorer#1]
I found they removed it from the AssetLib because LICENSE is misspelled. Can that be fixed and resubmitted?

**Comment by christinoleo** [comment]
Ah, I see. Ill fix that :)

**Comment by Salvakiya** [comment]
I still dont see it on the assetlib myself. Would be super useful

**Comment by christinoleo** [comment]
Finally I stopped to fix this. Thanks for letting me know of the issue!
