### ISSUE TITLE
Search for a font

### ISSUE THREAD

**Issue by MrEliptik** [christinoleo/godot-google-font-explorer#3]
First of all, thanks for your work, this is a great addon! 

My main struggle is the huge amount of fonts, and I feel like having a way to search for one would be awesome.
Are you still working on it? If not, do you want me to help?

**Comment by christinoleo** [comment]
Hey MrEliptik! Thanks!

I understand and agree with your point. I even started making the search functionality but then "real life work" got in the way. If you wish to try your hands on it, PRs are very welcome! If no external help come, I'll likely do the search functionality whenever I use the addon again (it should be one or to months before then, though).
